### ISSUE TITLE
Raw test data

### ISSUE THREAD

**Issue by Eric-11** [hahnicity/ventmode#1]
Just a question.  The raw test data located in raw_vwd and y_dir don't seem to contain any of the airway pressure and flow samples. Am I interpreting this correctly?

I'd like to run some of my own algorithms on the raw ventilator waveforms. Is that possible?

Thanks

**Comment by hahnicity** [comment]
hi Eric, please see the https://github.com/hahnicity/ventmap documentation
for what the data should look like. Raw data flow and airway pressure
samples are located in the raw_vwd directories. You can read the data with
python using the ventmap APIs.

**Comment by Eric-11** [comment]
Thanks. I've managed to parse the raw data to be continuous csv files for my simulations.Is the sample rate 50hz for all the data points? Is there a way to get the annotations for these waveforms?

Edit: Ok, nevermind I see how the timing encoding works from your ventmap tool.  Thanks again.

**Comment by hahnicity** [comment]
Yes, it's 50hz for all data in this dataset.

As for the annotations: we annotated the ventilator mode of each of these waveforms. The annotations are located in the y_dir directory. For practical purposes we focused on annotating "Volume Control" (vc), "Pressure Control" (pc), "Pressure Support" (ps), Continuous Positive Airway Pressure (cpap), and Proportional Assist Ventilation (pav). Other columns can be used like BN and ventBN to ensure that your raw data is matching your annotations.

**Comment by Eric-11** [comment]
Ok. Thank you very much.  We are trying to build some very simple algorithms for reading live airway pressures for emergency ventilators in an attempt to provide safer equipment.  This is all new to many of us so if you get a chance any comments would be helpful on our efforts.  https://github.com/Eric-11/ventilator-parameters

**Comment by Eric-11** [comment]
I've had a chance to look through some of the y_lim annotations and it is a little confusing. There are 3 missing columns and the first 3 columns don't really seem to match the data.

For example:

BN, vent BN, rel time
2189-06-14-00-44-11.544069:44:11.544069,372.0,3.28,

I don't see the BN in there. How should this data be related to the vwd?  Thanks.

**Comment by hahnicity** [comment]
Yeah, thanks for bringing this to my attention. It could be a bug in the anonymization scripts but I need to be sure first. For now, I'd suggest just raw and ground truth files with valid BN, vent BN, and rel time data.

**Comment by hahnicity** [comment]
Hi Eric, I have fixed this issue. I had to re-create the dataset because I needed to redo the files with the anonymization script but the issue is fixed.
