### ISSUE TITLE
Ventilator Waveform Data - doesn't match dict key

### ISSUE THREAD

**Issue by mpiffari** [hahnicity/ventmode#4]
Hi @hahnicity,
I run project and have an error.

I debug and saw that in datasets.py file at line 350, vwd dictionary doesn't contain key 't'. Please help me fix it.

`vwd = rel_bn 10

vent_bn 50576

flow [4.34, 5.65, 15.48, 34.19, 50.14, 62.83, 70.49, 72.01, 67.93, 65.34, 62.53, 59.74, 55.04, 53.19, 51.62, 48.79, 45.6, 40.45, 35.58, 32.64, 27.62, 24.36, 22.12, 19.25, 18.06, 15.86, 14.55, 12.66, 10.09, 8.26, 7.08, 5.69, 4.09, 3.16, 3.18, 2.85, 2.97, 2.23, 2.17, 1.54, 0.71, -30.23, -49.22, -52.65, -48.74, -47.89, -44.72, -42.21, -40.28, -38.62, -36.71, -36.19, -36.44, -34.3, -32.95, -30.73, -28.67, -26.41, -26.47, -25.63, -24.75, -23.85, -23.95, -22.03, -22.99, -20.92, -20.71, -19.48, -18.08, -16.99, -16.44, -16.05, -15.65, -13.98, -13.18, -11.85, -12.37, -12.38, -12.16, -11.27, -10.23, -9.2, -8.07, -6.78, -5.4, -3.45, -1.66, -0.47, 0.02, 0.77, 1.78, 2.65, 3.22]

pressure [4.84, 4.86, 5.43, 6.82, 8.44, 10.4, 12.82, 15.15, 16.22, 16.78, 17.15, 17.44, 17.38, 17.27, 17.27, 17.55, 17.82, 17.86, 17.86, 17.87, 17.86, 17.78, 17.68, 17.54, 17.57, 17.49, 17.45, 17.39, 17.55, 17.34, 17.29, 17.38, 17.22, 17.05, 17.06, 17.03, 16.99, 17.09, 17.14, 17.24, 17.22, 17.19, 15.36, 11.88, 9.52, 8.83, 8.45, 8.25, 8.19, 8.01, 7.9, 7.85, 7.71, 7.45, 7.4, 7.39, 7.24, 7.17, 7.25, 7.29, 7.13, 7.08, 7.08, 6.87, 6.89, 6.9, 6.8, 6.85, 6.81, 6.71, 6.69, 6.68, 6.58, 6.54, 6.37, 6.32, 6.32, 6.41, 6.4, 6.22, 6.27, 6.2, 6.09, 5.97, 5.84, 5.73, 5.77, 5.7, 5.69, 5.73, 5.73, 5.59, 5.39]

bs_time 18.44

frame_dur 1.86

dt 0.02

abs_bs 2188-04-12 00-34-13.365285`

`Traceback (most recent call last):
  File "main.py", line 944, in <module>
    main()
  File "main.py", line 904, in main
    df = feature_set.create_learning_df()
  File "c:\users\miche\onedrive\desktop\tesi magistrale\materiale\ventmode\ventmode\datasets.py", line 577, in create_learning_df
    df, all_vwd, all_bm = self.get_features_and_annos()
  File "c:\users\miche\onedrive\desktop\tesi magistrale\materiale\ventmode\ventmode\datasets.py", line 414, in get_features_and_annos
    x, all_breath_vwd, all_breath_metadata = self.get_features(tor_results=tor_results, random_thresh=random_thresh, dtw_n_lookback=dtw_n_lookback, dtw_thresh=dtw_thresh, dtw_rolling_av_len=dtw_rolling_av_len)
  File "c:\users\miche\onedrive\desktop\tesi magistrale\materiale\ventmode\ventmode\datasets.py", line 350, in get_features
    pressure_itime = calc_pressure_itime_from_front(vwd['t'], vwd['pressure'], median_pip, median_peep, .4)
KeyError: 't'` `

**Comment by hahnicity** [comment]
Hi Piffo,

I have fixed this issue. If you have cloned the repo can you do a pull? 

```
git pull origin master
```

If you have forked, you will need to do a pull from [upstream master](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

Greg

**Comment by mpiffari** [comment]
Hi @hahnicity ,
thanks a lot for you fast bug fix.

Can you explain me in short now which time 't' represent? Is it the difference between initial timestamp of actual breat and the timestamp of next one?

**Comment by hahnicity** [comment]
`'t'` just stands for the number of relative seconds that have elapsed since the breath started. So say for instance that you look at the flow information, and then you just want to see the observation at index 10. You would do
```
breath['flow'][10]
```
Then say you wanted to see how many seconds had elapsed from breath start at index 10 you would do
```
breath['t'][10]
```

**Comment by mpiffari** [comment]
Hi @hahnicity,
I found same problem on ventMAP repository: the problem is located here
```
  File "...\anaconda3\envs\ventmap\lib\site-packages\ventmap\breath_meta.py", line 262, in get_experimental_breath_meta
    rel_time_array = breath["t"]
```

It is the same bug as the ventmode repo?

**Comment by hahnicity** [comment]
Hi @Piffo , yes this is basically the same bug. I have fixed it. Please do
```
pip install -U ventmap
```
to fix the issue
