### ISSUE TITLE
Incompatible Python version

### ISSUE THREAD

**Issue by mpiffari** [hahnicity/ventmode#5]
Hello again @hahnicity,
I'm getting problems during installation of Pytorch with Python 2.7 for ventmode.

The error says:
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch -> python[version='2.7.*|3.5.*|3.6.*|3.6.9|3.6.9|3.6.9|3.6.9|>=3.9,<3.10.0a0|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|3.4.*',build='0_73_pypy|3_73_pypy|2_73_pypy|1_73_pypy']
  - pytorch -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

Is it possible to use newer Python version?

**Comment by hahnicity** [comment]
Hi Michele,

I haven't tested ventmode on python 3. So I wouldn't recommend trying to upgrade. Currently my thought is that you can try going to the [pytorch main website](https://pytorch.org/get-started/locally/) and installing it via instructions there. But you don't need pytorch to run the main machine learning work. You only need it if you want to look at the LSTM. However the work there is mostly experimental, and I didn't dive too deeply into making it work.

Greg

**Comment by hahnicity** [comment]
Closing because this has been updated to Py3
